model:
  channels: 32
  num_blocks: 7
  semantic_classes: 6 # chair column floor table wall clutter
  instance_classes: 6
  sem2ins_classes: [2] # use floor as direct instance; note: s3dis use floor and ceil as instance directly
  semantic_only: False
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.008 # previous 0.002 # s3dis's radius is 0.04, about 2*1/scale=0.02
    mean_active: 300
    # class_numpoint_mean: [1823, 7457, 6189, 7424, 34229, 1724, 5439, 6016, 39796, 5279, 5092, 12210, 10225]
    # class_numpoint_mean: [49000, 101387, 16227406,190000, 2000000, 882470] # TODO?
    class_numpoint_mean: [98791, 101072, 5621760, 552629, 1584834, 3378041] # computed using a script "compute_median_points_each_instance.py"
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [3] # same as sem2ins_classes
  instance_voxel_cfg:
    scale: 1000 # the point coordinates are scaled up for voxelization; sub-sampling grid size = 1/scale=0.001
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: True
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear']

data:
  train:
    type: '5gdataset'
    data_root: 'dataset/5gdataset/preprocess'
    prefix: ['Area_1', 'Area_2', 'Area_3']
    suffix: '_inst_nostuff.pth'
    repeat: 20
    training: True
    voxel_cfg:
      # scale: 1000
      scale: 250 # S3DISis 50, with resolution about 1/50=0.02
      spatial_shape: [128, 512]
      # max_npoint: 4000000
      max_npoint: 250000  # max number of points after random crop
      min_npoint: 5000  # min number of points after random crop
  test:
    type: '5gdataset'
    data_root: 'dataset/5gdataset/preprocess'
    prefix: 'Area_4' # for testing , use the Area_5
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      # scale: 1000
      scale: 250 # S3DISis 50, with resolution about 1/50=0.02
      spatial_shape: [128, 512]
      max_npoint: 250000  # no effect during testing
      min_npoint: 5000  # no effect during testing

dataloader:
  train:
    batch_size: 2 # 4
    num_workers: 2 # 4
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.002 # 4 GPUs use 0.004, otherwise reduce the lr linearly; check its github issues

save_cfg:
  semantic: True
  offset: True
  instance: True

fp16: False
epochs: 30
step_epoch: 0
save_freq: 2
pretrain: 'work_dirs/softgroup_5gdataset_backbone_fold5/latest.pth'
work_dir: ''
